camera:
  camera:
    ros__parameters:
      device_type: ''
      serial_no: ''
      usb_port_id: ''

      # color_fps: 15.0
      # color_width: 640
      # color_height: 480
      # color_qos: "DEFAULT"

      # depth_fps: 15.0
      # depth_width: 640
      # depth_height: 480
      # depth_qos: "DEFAULT"

      # infra_width: 640
      # infra_height: 480
      # infra_qos: "DEFAULT"

      gyro_fps: 200
      accel_fps: 100

      # pointcloud.enable: true
      # filters: 'pointcloud'

      enable_color: true
      enable_depth: true
      enable_gyro: true
      enable_accel: false
      # enable_infra1: true
      # enable_infra2: true

      enable_fisheye1: false
      enable_fisheye2: false

      # pointcloud_texture_index: 0
      # pointcloud_texture_stream: RS2_STREAM_ANY

      # stereo_module:
      #   emitter_enabled: 0
      # unite_imu_method: ''

      # rosbag_filename: ''

      # initial_reset: true

      # diagnostics_period: 1.0

# ros2 launch realsense2_camera rs_launch.py config_file:="'/pippino_ws/src/d455_wrapper4.0.yaml'"