amcl:
  ros__parameters:
    use_sim_time: False
    alpha1: 0.02
    alpha2: 0.2
    alpha3: 0.02
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_link"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: False
    global_frame_id: "map"
    lambda_short: 0.1
    initial_pose: 
      x: 3.30
      y: -0.55
      z: 0.0
      yaw: 0.0
    set_initial_pose: True
    laser_likelihood_max_dist: 2.0
    laser_max_range: 12.0
    laser_min_range: 0.2
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 2000
    min_particles: 500
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.001
    recovery_alpha_slow: 0.001
    resample_interval: 1
    # robot_model_type: "differential"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: True
    transform_tolerance: 1.0
    update_min_a: 0.2
    update_min_d: 0.25
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    scan_topic: scan
    map_topic: map


amcl_map_client:
  ros__parameters:
    use_sim_time: False

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: False

bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: map
    robot_base_frame: base_link
    odom_topic: odometry/filtered
    transform_tolerance: 0.1
    bt_loop_duration: 10
    default_server_timeout: 20
    default_nav_to_pose_bt_xml: "/home/michele/pippino_ws/src/pippino_navigation/config/bt_navigate_to_pose.xml"
    goal_blackboard_id: goal
    goals_blackboard_id: goals
    path_blackboard_id: path
    plugin_lib_names:
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_compute_path_through_poses_action_bt_node
    # - nav2_smooth_path_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_spin_action_bt_node
    - nav2_wait_action_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_goal_updated_condition_bt_node
    - nav2_initial_pose_received_condition_bt_node
    - nav2_reinitialize_global_localization_service_bt_node
    - nav2_rate_controller_bt_node
    - nav2_distance_controller_bt_node
    - nav2_speed_controller_bt_node
    - nav2_truncate_path_action_bt_node
    - nav2_goal_updater_node_bt_node
    - nav2_recovery_node_bt_node
    - nav2_pipeline_sequence_bt_node
    - nav2_round_robin_node_bt_node
    - nav2_transform_available_condition_bt_node
    - nav2_time_expired_condition_bt_node
    - nav2_distance_traveled_condition_bt_node
    - nav2_single_trigger_bt_node
    # - nav2_is_battery_low_condition_bt_node
    - nav2_navigate_through_poses_action_bt_node
    - nav2_navigate_to_pose_action_bt_node
    - nav2_remove_passed_goals_action_bt_node
    - nav2_planner_selector_bt_node
    - nav2_controller_selector_bt_node
    - nav2_goal_checker_selector_bt_node

bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: False

controller_server:
  ros__parameters:
    use_sim_time: False
    controller_frequency: 6.0
    min_x_velocity_threshold: 0.01 # 0.001
    min_y_velocity_threshold: 0.5 # 0.5
    min_theta_velocity_threshold: 0.01
    progress_checker_plugin: "progress_checker"
    goal_checker_plugin: "goal_checker"
    controller_plugins: ["FollowPath"]
    odom_topic: odometry/filtered
    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0
    # Goal checker parameters
    # goal_checker:
    #   plugin: "nav2_controller::SimpleGoalChecker"
    #   xy_goal_tolerance: 0.25
    #   yaw_goal_tolerance: 0.05
    #   stateful: True
    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.0.001
    # # DWB parameters
    # FollowPath:
    #   plugin: "dwb_core::DWBLocalPlanner"
    #   debug_trajectory_details: True
    #   min_vel_x: 0.0
    #   min_vel_y: 0.0
    #   max_vel_x: 0.24
    #   max_vel_y: 0.0
    #   max_vel_theta: 0.8
    #   min_speed_xy: 0.0
    #   max_speed_xy: 0.24
    #   min_speed_theta: 0.0
    #   acc_lim_x: 0.4
    #   acc_lim_y: 0.0
    #   acc_lim_theta: 0.6
    #   decel_lim_x: -1.5
    #   decel_lim_y: 0.0
    #   decel_lim_theta: -1.2
    #   vx_samples: 20
    #   vy_samples: 5
    #   vtheta_samples: 20
    #   sim_time: 1.7
    #   linear_granularity: 0.05
    #   angular_granularity: 0.025
    #   transform_tolerance: 0.2
    #   xy_goal_tolerance: 0.25
    #   trans_stopped_velocity: 0.25
    #   short_circuit_trajectory_evaluation: True
    #   stateful: True
    #   critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
    #   BaseObstacle.scale: 0.02
    #   PathAlign.scale: 32.0
    #   PathAlign.forward_point_distance: 0.1
    #   GoalAlign.scale: 24.0
    #   GoalAlign.forward_point_distance: 0.1
    #   PathDist.scale: 32.0
    #   GoalDist.scale: 24.0
    #   RotateToGoal.scale: 32.0
    #   RotateToGoal.slowing_factor: 5.0
    #   RotateToGoal.lookahead_time: -1.0
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.20
      lookahead_dist: 0.6
      min_lookahead_dist: 0.3
      max_lookahead_dist: 0.9
      lookahead_time: 0.8
      rotate_to_heading_angular_vel: 0.6
      transform_tolerance: 0.1
      use_velocity_scaled_lookahead_dist: True
      min_approach_linear_velocity: 0.04
      max_allowed_time_to_collision_up_to_carrot: 1.0
      use_regulated_linear_velocity_scaling: True
      use_cost_regulated_linear_velocity_scaling: True
      regulated_linear_scaling_min_radius: 0.6
      regulated_linear_scaling_min_speed: 0.08
      use_rotate_to_heading: True
      allow_reversing: False
      rotate_to_heading_min_angle: 0.785
      max_angular_accel: 1.6
controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False


local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 5.0
      footprint_padding: 0.02
      global_frame: odom
      robot_base_frame: base_link
      footprint: '[ [0.07, 0.15], [-0.3, 0.15], [-0.3, -0.15], [0.07, -0.15] ]'
      use_sim_time: False
      rolling_window: True
      width: 3
      height: 3
      resolution: 0.04
      static_map: False
      plugins: ["obstacle_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 1.5
        cost_scaling_factor: 5.0
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan tilting_cloud tilting_cloud_clearing
        footprint_clearing_enabled: True
        max_obstacle_height: 2.0
        combination_method: 1
        scan:
          topic: /scan
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          max_obstacle_height: 2.0
          min_obstacle_height: 0.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          inf_is_valid: True
        tilting_cloud:
          topic: /D455/depth/color/points
          min_obstacle_height: 0.03
          max_obstacle_height: 0.5
          clearing: False
          marking: True
          data_type: "PointCloud2"
        tilting_cloud_clearing:
          topic: /D455/depth/color/points
          min_obstacle_height: 0.00
          max_obstacle_height: 1.0
          clearing: True
          marking: False
          data_type: "PointCloud2"
      # voxel_layer:
      #   plugin: "nav2_costmap_2d::VoxelLayer"
      #   enabled: True
      #   footprint_clearing_enabled: True
      #   max_obstacle_height: 2.0
      #   publish_voxel_map: True
      #   origin_z: 0.0
      #   z_resolution: 0.05
      #   z_voxels: 16
      #   unknown_threshold: 15
      #   mark_threshold: 2
      #   combination_method: 1
      #   observation_sources: scan tilting_cloud tilting_cloud_clearing
      #   scan:
      #     topic: /scan
      #     max_obstacle_height: 1.0
      #     clearing: True
      #     marking: True
      #     data_type: "LaserScan"
      #   tilting_cloud:
      #     topic: /D455/depth/color/points
      #     min_obstacle_height: 0.03
      #     max_obstacle_height: 2.0
      #     clearing: False
      #     marking: True
      #     data_type: "PointCloud2"
      #   tilting_cloud_clearing:
      #     topic: /D455/depth/color/points
      #     min_obstacle_height: 0.00
      #     max_obstacle_height: 2.0
      #     clearing: True
      #     marking: False
    local_costmap_client:
      ros__parameters:
        use_sim_time: False
    local_costmap_rclcpp_node:
      ros__parameters:
        use_sim_time: False

global_costmap:
  global_costmap:
    ros__parameters:
      footprint_padding: 0.03
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: False
      # robot_radius: 0.22 # radius set and used, so no footprint points
      footprint_padding: 0.02
      footprint: '[ [0.07, 0.15], [-0.3, 0.15], [-0.3, -0.15], [0.07, -0.15] ]'
      resolution: 0.05
      plugins: ["static_layer", "obstacle_layer", "voxel_layer", "inflation_layer" ]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan #pointcloud
        footprint_clearing_enabled: True
        max_obstacle_height: 0.5
        combination_method: 1
        scan:
          topic: /scan
          obstacle_max_range: 1.5
          obstacle_min_range: 0.0
          raytrace_max_range: 2.0
          raytrace_min_range: 0.0
          max_obstacle_height: 0.5
          min_obstacle_height: 0.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          inf_is_valid: False
        # pointcloud:
        #   topic: /D455/depth/color/points
        #   obstacle_max_range: 1.5
        #   obstacle_min_range: 0.0
        #   raytrace_max_range: 2.0
        #   raytrace_min_range: 0.0
        #   max_obstacle_height: 0.5
        #   min_obstacle_height: 0.05
        #   clearing: True
        #   marking: True
        #   data_type: "PointCloud2"
        #   inf_is_valid: False
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        footprint_clearing_enabled: True
        max_obstacle_height: 0.5
        publish_voxel_map: False
        origin_z: 0.0
        z_resolution: 0.03
        z_voxels: 16
        unknown_threshold: 15
        mark_threshold: 0
        observation_sources: tilting_cloud
        combination_method: 1
        tilting_cloud:
          topic: /D455/depth/color/points
          obstacle_max_range: 1.5
          obstacle_min_range: 0.0
          min_obstacle_height: 0.02
          max_obstacle_height: 0.30
          clearing: False
          marking: True
          data_type: "PointCloud2"
        tilting_cloud_clearing:
          topic: /D455/depth/color/points
          obstacle_max_range: 1.5
          obstacle_min_range: 0.2
          min_obstacle_height: 0.0
          max_obstacle_height: 0.5
          clearing: True
          marking: False
          data_type: "PointCloud2"
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
        enabled: True
        subscribe_to_updates: True
        transform_tolerance: 0.1
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: True
        inflation_radius: 0.8
        cost_scaling_factor: 6.0
        inflate_unknown: False
        inflate_around_unknown: True
      always_send_full_costmap: True

map_server:
  ros__parameters:
    yaml_filename: "upper_floor.yaml"

map_saver:
  ros__parameters:
    save_map_timeout: 5000
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: False

planner_server:
  ros__parameters:
    expected_planner_frequency: 0.5
    use_sim_time: False
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      # tolerance: 0.5
      # use_astar: False
      # allow_unknown: True


planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False

smoother_server:
  ros__parameters:
    use_sim_time: False

recoveries_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    recovery_plugins: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_recoveries/Spin"
    backup:
      plugin: "nav2_recoveries/BackUp"
    wait:
      plugin: "nav2_recoveries/Wait"
    global_frame: odom
    robot_base_frame: base_link
    transform_tolerance: 0.1
    use_sim_time: False
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2

robot_state_publisher:
  ros__parameters:
    use_sim_time: False

waypoint_follower:
  ros__parameters:
    loop_rate: 20
    stop_on_failure: False
    waypoint_task_executor_plugin: "wait_at_waypoint"   
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200
