# Request type defines which actuator has to be set:
# - '0' cancel current action
# - '1' find aruco
# - '2' map the room

int8 action_type
string map_url
---
bool success   # indicate successful run of triggered service
