FROM pippino/ros2:base
# FROM dustynv/ros:foxy-ros-base-l4t-r32.5.0

# To avoid waiting for input during package installation
ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONPATH=$PYTHONPATH:/usr/local/lib

ENV LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
CMD ["bash"]
# RUN apt-get update && apt-get -y upgrade

RUN apt-get update && apt-get upgrade && apt-get install -y --no-install-recommends \    
    build-essential \
    python3-vcstool \
    cmake \
    libusb-1.0-0 \
    udev \
    apt-transport-https \
    ca-certificates \
    curl \
    git \
    clang-tidy \
    flex \
    usbutils \
    python3-rosdep \
    ros-galactic-rmw-fastrtps-shared-cpp \
    ros-galactic-rosidl-typesupport-fastrtps-cpp \
    software-properties-common

RUN mkdir -p /services_ws/src && cd /services_ws/src \
    && git clone https://github.com/micro-ROS/micro_ros_setup.git -b galactic --depth 1 \
    && git clone -b ros2 https://github.com/slamtec/rplidar_ros.git --depth 1

    # && git clone https://github.com/iPajaz/pippino.git --depth 1 \
    # && git clone https://github.com/ros/joint_state_publisher.git -b galactic --depth 1
    # && git clone https://github.com/ros/xacro.git -b ros2 --depth 1 --single-branch

WORKDIR /services_ws

RUN sudo rosdep init \
    && rosdep update

RUN rosdep install --from-paths src --ignore-src --rosdistro galactic -y

SHELL ["/bin/bash", "-c"]

RUN source /opt/ros/galactic/setup.bash \
    && colcon build

RUN source /opt/ros/galactic/setup.bash \
    && source install/local_setup.bash \
    && ros2 run micro_ros_setup create_agent_ws.sh \
    && ros2 run micro_ros_setup build_agent.sh

RUN echo 'source /services_ws/install/local_setup.bash' >> /root/.bashrc
RUN echo 'source /pippino_ws/install/local_setup.bash' >> /root/.bashrc

RUN echo "alias run='ros2 launch pippino_bringup pippino.launch.py'" >> /root/.bashrc

WORKDIR /root