ARG BASE_IMAGE=test/test

FROM $BASE_IMAGE
# FROM dustynv/ros:galactic-ros-base-l4t-r32.6.1


# To avoid waiting for input during package installation
ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONPATH=$PYTHONPATH:/usr/local/lib

ARG ROS_DISTRO=foxy

ENV LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
CMD ["bash"]

RUN apt-get update && apt-get install -y --no-install-recommends \    
    build-essential \
    python3-vcstool \
    cmake \
    libusb-1.0-0 \
    udev \
    apt-transport-https \
    ca-certificates \
    curl \
    git \
    clang-tidy \
    flex \
    usbutils \
    python3-rosdep \
    ros-${ROS_DISTRO}-rmw-fastrtps-shared-cpp \
    ros-${ROS_DISTRO}-rosidl-typesupport-fastrtps-cpp \
    software-properties-common

RUN mkdir -p /services_ws/src && cd /services_ws/src \
    && git clone https://github.com/micro-ROS/micro_ros_setup.git -b ${ROS_DISTRO} --depth 1 --single-branch \
    && git clone -b ros2 https://github.com/iPajaz/rplidar_ros.git --depth 1

    # && git clone https://github.com/iPajaz/pippino.git --depth 1 \
    # && git clone https://github.com/ros/joint_state_publisher.git -b ${ROS_DISTRO} --depth 1
    # && git clone https://github.com/ros/xacro.git -b ros2 --depth 1 --single-branch

RUN mkdir -p /nav2_ws/src && cd /nav2_ws/src \
    && git clone https://github.com/ros-planning/navigation2.git -b galactic --depth 1 --single-branch \
    && git clone https://github.com/BehaviorTree/BehaviorTree.CPP.git --depth 1 --single-branch

RUN sudo rosdep init \
    && rosdep update

WORKDIR /nav2_ws

RUN rosdep install --from-paths src --ignore-src --rosdistro ${ROS_DISTRO} -y

SHELL ["/bin/bash", "-c"]

RUN source /opt/ros/${ROS_DISTRO}/setup.bash \
    && colcon build --symlink-install

WORKDIR /services_ws

RUN rosdep install --from-paths src --ignore-src --rosdistro ${ROS_DISTRO} -y


RUN source /opt/ros/${ROS_DISTRO}/setup.bash \
    && colcon build

RUN source /opt/ros/${ROS_DISTRO}/setup.bash \
    && source install/local_setup.bash \
    && ros2 run micro_ros_setup create_agent_ws.sh \
    && ros2 run micro_ros_setup build_agent.sh

RUN echo 'source /services_ws/install/local_setup.bash' >> /root/.bashrc
RUN echo 'source /pippino_ws/install/local_setup.bash' >> /root/.bashrc

RUN echo "alias run='ros2 launch pippino_bringup pippino.launch.py'" >> /root/.bashrc

RUN apt-get install -y --no-install-recommends \
    ros-${ROS_DISTRO}-xacro \
    ros-${ROS_DISTRO}-joint-state-publisher \
    ros-${ROS_DISTRO}-depth-image-proc \
    ros-${ROS_DISTRO}-robot-localization

WORKDIR /root

ENTRYPOINT ["/pippino_ws/src/pippino-services-entrypoint.sh"]