FROM dustynv/ros:foxy-ros-base-l4t-r32.6.1

# To avoid waiting for input during package installation
ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONPATH=$PYTHONPATH:/usr/local/lib

ENV LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH

RUN apt-get update && apt-get -y upgrade

RUN apt-get install -y --no-install-recommends \    
    build-essential \
    cmake \
    libusb-1.0-0 \
    udev \
    apt-transport-https \
    ca-certificates \
    curl \
    git \
    software-properties-common \
    && rm -rf /var/lib/apt/lists/*


RUN echo 'source /pippino_ws/install/local_setup.bash' >> /root/.bashrc

RUN echo "alias run='ros2 launch pippino_bringup pippino.launch.py'" >> /root/.bashrc



# RUN cd /pippino_ws \
#     apt-get update \
#     && sudo rosdep init \
#     && rosdep update \
#     && rosdep install --from-paths src --ignore-src --rosdistro $ROS_DISTRO -y \
#     && colcon build \
#     && ros2 run micro_ros_setup create_agent_ws.sh \
#     && ros2 run micro_ros_setup build_agent.sh

